name = "MarkImg"
uuid = "4c2c6eba-bd50-42d0-b4ea-ca36516133f1"
authors = ["donghoon <mdhe1248@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
